version: '3.6'

services:
    custompios:
#        environment:
#        - BUILD_VARIANT=rockpi4b
        image: guysoft/custompios:devel
        container_name: ratos-build
        tty: true
        restart: always
        privileged: true
        volumes:
        - ./src/:/distro
        devices:
        - /dev/loop-control
